### ISSUE TITLE
Opportunity to decrease bundle size by removing unneeded moment packages

### ISSUE THREAD

**Issue by IamTechknow** [samliebow/viewfinder#11]
Hi there, I'm a new HiR and have been using this for interviews, and it works great for me.

I noticed that the production mode webpack bundle size is quite big, about 441 kilobytes. I encountered this before - when moment is used, all the locales for moment.js are included by default. It's very easy to make it so only the default locale (English) is included, which decreases the bundle size to 266 KB, a large decrease.

This fix is pretty simple, here's a [guide](https://medium.com/@michalozogan/how-to-split-moment-js-locales-to-chunks-with-webpack-de9e25caccea) for it. I could also put in a PR

**Comment by samliebow** [comment]
Put in a PR and then put it on your resume!

I believe @GaoR is the current maintainer. (And we should have a better process for handing this off so it's obvious...)

**Comment by IamTechknow** [comment]
Sounds good, I can put in a PR and hopefully put in another PR to fix a pesky bug in Firefox. As long as @GaoR has push permissions I reckon that's good.
